# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
run:
  timeout: 5m
  tests: false # Skip linter checks on unit test files

linters-settings:
  dupl:
    threshold: 200 # TODO: reduce to 100
  misspell:
    locale: US
  cyclop:
    max-complexity: 24 # TODO: gradually lower these values to 10/5.0
    package-average: 9

  unparam:
    check-exported: false

  gosec:
    includes:
      - G401
      - G306
      - G101
      - G102
      - G103
      - G104
      - G106
      - G107
      - G108
      - G109
      - G110

linters:
  fast: false
  disable-all: false
  enable:
    #    - bodyclose # false positives, even with nolint directive applied
    - cyclop
    - dupl
    - errcheck
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - goimports
