# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  tests: false

linters:
  enable:
    - cyclop
    - dupl
    - gosec
    - misspell
    - nilerr
    - unconvert
    - unparam
  settings:
    cyclop:
      max-complexity: 24
      package-average: 9
    dupl:
      threshold: 200
    gosec:
      includes:
        - G401
        - G306
        - G101
        - G102
        - G103
        - G104
        - G106
        - G107
        - G108
        - G109
        - G110
    misspell:
      locale: US
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
