# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "*.md", 
  ".github/*", 
  "VERSION", 
  "go.mod", 
  "go.sum", 
  ".gitignore", 
  "configs/*",
  "placeholder.txt",
  "test-plan/**"
]
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
