apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IntelClusterTemplate
metadata:
  name: baseline-v2.0.1
  namespace: 53cd37b9-66b2-4cc8-b080-3722ed7af64a
spec:
  template:
    metadata: {}
    spec: {}
