# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Generated OIDC Mock Server Configuration (Dynamic Keys)
# This configuration provides a mock OIDC server with runtime-generated RSA keys

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-mock
  namespace: default
  labels:
    app: oidc-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc-mock
  template:
    metadata:
      labels:
        app: oidc-mock
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: oidc-mock-nginx-config
      - name: content
        configMap:
          name: oidc-mock-content
---
apiVersion: v1
kind: Service
metadata:
  name: platform-keycloak
  namespace: orch-platform
spec:
  selector:
    app: oidc-mock
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ExternalName
  externalName: oidc-mock.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: oidc-mock
  namespace: default
spec:
  selector:
    app: oidc-mock
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-mock-nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location /realms/master/.well-known/openid-configuration {
            return 200 '{
                "issuer": "http://platform-keycloak.orch-platform.svc/realms/master",
                "authorization_endpoint": "http://platform-keycloak.orch-platform.svc/realms/master/protocol/openid-connect/auth",
                "token_endpoint": "http://platform-keycloak.orch-platform.svc/realms/master/protocol/openid-connect/token",
                "jwks_uri": "http://platform-keycloak.orch-platform.svc/realms/master/keys",
                "userinfo_endpoint": "http://platform-keycloak.orch-platform.svc/realms/master/protocol/openid-connect/userinfo",
                "response_types_supported": ["code", "token", "id_token", "code token", "code id_token", "token id_token", "code token id_token"],
                "subject_types_supported": ["public"],
                "id_token_signing_alg_values_supported": ["PS512", "RS256"]
            }';
            add_header Content-Type application/json;
        }
        
        location /realms/master/keys {
            return 200 '{"keys":[{"alg":"PS512","e":"AQAB","kid":"cluster-tests-key","kty":"RSA","n":"5tPh9mVkivcEXfD0fQjgrh-HpaKH3Gu8EM9_v-O4A26AWDRbKKTGTkTWW1Xm60S5AbSphtkDXCGHuU7fN1ylI5E9sD8ZL_lIZbDmHi51oFrQ4fKjApglKFL4vdxmKDVQMCL4eXd4Ww2OmhEgtFg7DqwT8oAgjjsvGc6e0hErzDanF32qVSg7AmfW12AgLfDGv0bUCSlxGBudaIIYufroJvZOIsWr51Ol51Ea5njKLxYRpkhIZejtDMZIQiAmTwyAYHpGh0D8lWgtvbrDTsIibJTiqn59IbNGwNaRCZJPHtZ2pxhovFmrr7jAyPbaNLW5oIMCYbEFtqlhuNve5CJcHw","use":"sig"}]}';
            add_header Content-Type application/json;
        }
        
        location / {
            return 200 'OIDC Mock Server (Dynamic Keys)\nAvailable endpoints:\n  /realms/master/.well-known/openid-configuration\n  /realms/master/keys\n';
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-mock-content
  namespace: default
data:
  jwks.json: |
    {"keys":[{"alg":"PS512","e":"AQAB","kid":"cluster-tests-key","kty":"RSA","n":"5tPh9mVkivcEXfD0fQjgrh-HpaKH3Gu8EM9_v-O4A26AWDRbKKTGTkTWW1Xm60S5AbSphtkDXCGHuU7fN1ylI5E9sD8ZL_lIZbDmHi51oFrQ4fKjApglKFL4vdxmKDVQMCL4eXd4Ww2OmhEgtFg7DqwT8oAgjjsvGc6e0hErzDanF32qVSg7AmfW12AgLfDGv0bUCSlxGBudaIIYufroJvZOIsWr51Ol51Ea5njKLxYRpkhIZejtDMZIQiAmTwyAYHpGh0D8lWgtvbrDTsIibJTiqn59IbNGwNaRCZJPHtZ2pxhovFmrr7jAyPbaNLW5oIMCYbEFtqlhuNve5CJcHw","use":"sig"}]}
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>OIDC Mock Server (Dynamic Keys)</title></head>
    <body>
    <h1>OIDC Mock Server</h1>
    <p><strong>Using Runtime-Generated Keys</strong></p>
    <p>Available endpoints:</p>
    <ul>
    <li><a href="/realms/master/.well-known/openid-configuration">/.well-known/openid-configuration</a></li>
    <li><a href="/realms/master/keys">/keys</a></li>
    </ul>
    </body>
    </html>
