# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Namespace}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IntelMachineBinding
metadata:
  name: intel-rke2-test-{{.Namespace}}
  namespace: {{.Namespace}}
spec:
  clusterName: intel-rke2-test
  intelMachineTemplateName: baseline-clusterclass-v0.0.1-controlplane
  nodeGUID: {{.NodeGUID}}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IntelMachineTemplate
metadata:
  name: baseline-clusterclass-v0.0.1-controlplane
  namespace: {{.Namespace}}
spec:
  template:
    spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlaneTemplate
metadata:
  name: baseline-clusterclass-v0.0.1
  namespace: {{.Namespace}}
spec:
  template:
    spec:
      agentConfig:
        additionalUserData: {}
        format: cloud-config
        kubelet:
          extraArgs:
          - --topology-manager-policy=best-effort
          - --cpu-manager-policy=static
          - --reserved-cpus=1
          - --max-pods=250
          - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: IntelMachineTemplate
        name: baseline-clusterclass-v0.0.1-controlplane
      machineTemplate:
        infrastructureRef: {}
        metadata: {}
      manifestsConfigMapReference:
        apiVersion: v1
        kind: ConfigMap
        name: coredns-config
        namespace: default
      nodeDrainTimeout: 2m0s
      privateRegistriesConfig:
        mirrors:
          rs-proxy.rs-proxy.svc.cluster.local:8443:
            endpoint:
            - https://localhost.internal:9443
      rolloutStrategy:
        rollingUpdate:
          maxSurge: 1
        type: RollingUpdate
      serverConfig:
        cni: calico
        cniMultusEnable: true
        disableComponents:
          kubernetesComponents:
          - cloudController
        etcd:
          backupConfig:
            retention: "5"
            scheduleCron: 0 */5 * * *
          customConfig:
            extraArgs:
            - cipher-suites=[TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_CHACHA20_POLY1305_SHA256]
        kubeAPIServer:
          extraArgs:
          - --feature-gates=PortForwardWebsockets=true
          - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        kubeControllerManager: {}
        kubeScheduler: {}
      version: ""
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IntelClusterTemplate
metadata:
  name: baseline-clusterclass-v0.0.1
  namespace: {{.Namespace}}
spec:
  template:
    metadata: {}
    spec: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: baseline-clusterclass-v0.0.1
  namespace: {{.Namespace}}
spec:
  controlPlane:
    machineHealthCheck:
      unhealthyConditions:
      - status: Unknown
        timeout: 5m0s
        type: Ready
      - status: "False"
        timeout: 5m0s
        type: Ready
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: IntelMachineTemplate
        name: baseline-clusterclass-v0.0.1-controlplane
        namespace: {{.Namespace}}
    metadata: {}
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: RKE2ControlPlaneTemplate
      name: baseline-clusterclass-v0.0.1
      namespace: {{.Namespace}}
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: IntelClusterTemplate
      name: baseline-clusterclass-v0.0.1
      namespace: {{.Namespace}}
  workers: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: intel-rke2-test
  namespace: {{.Namespace}}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.128.0.0/12
  topology:
    class: baseline-clusterclass-v0.0.1
    controlPlane:
      metadata: {}
      replicas: 1
    version: v1.30.6+rke2r1
