# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Namespace}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: intel-rke2-test
  namespace: {{.Namespace}}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.45.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.46.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: RKE2ControlPlane
    name: intel-rke2-test-control-plane-and-worker
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: IntelCluster
    name: intel-rke2-test
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IntelCluster
metadata:
  name: intel-rke2-test
  namespace: {{.Namespace}}
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: intel-rke2-test-control-plane-and-worker
  namespace: {{.Namespace}}
spec:
  agentConfig:
    nodeLabels:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: IntelMachineTemplate
    name: controlplane-and-worker
  nodeDrainTimeout: 2m
  registrationMethod: control-plane-endpoint
  replicas: 1
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  serverConfig:
    disableComponents:
      kubernetesComponents:
        - cloudController
  version: v1.30.6+rke2r1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IntelMachineTemplate
metadata:
  name: controlplane-and-worker
  namespace: {{.Namespace}}
spec:
  template: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: intel-rke2-test-agent
  namespace: {{.Namespace}}
spec:
  template:
    spec:
      agentConfig: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IntelMachineBinding
metadata:
  name: intel-machinebinding
  namespace: {{.Namespace}}
spec:
  nodeGUID: {{.NodeGUID}}
  clusterName: intel-rke2-test
  intelMachineTemplateName: controlplane-and-worker