#!/usr/bin/env bash
set -euo pipefail

# vEN bootstrap helper for cluster-tests.
#
# This script is intentionally minimal: it does NOT provision a VM.
# It validates that required vEN inputs are present and writes `.ven.env`
# (sourced by Makefile targets) so Ginkgo tests receive NODEGUID/SSH config.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

EDGE_NODE_PROVIDER="${EDGE_NODE_PROVIDER:-}" 
if [[ "${EDGE_NODE_PROVIDER,,}" != "ven" ]]; then
  echo "ERROR: scripts/ven/bootstrap.sh expects EDGE_NODE_PROVIDER=ven" >&2
  exit 2
fi

NODEGUID="${NODEGUID:-${VEN_NODEGUID:-}}"
VEN_SSH_HOST="${VEN_SSH_HOST:-}"
VEN_SSH_USER="${VEN_SSH_USER:-root}"
VEN_SSH_PORT="${VEN_SSH_PORT:-22}"
VEN_SSH_KEY="${VEN_SSH_KEY:-}"

if [[ -z "$NODEGUID" ]]; then
  echo "ERROR: NODEGUID (or VEN_NODEGUID) must be set for vEN mode" >&2
  exit 2
fi

if [[ -z "$VEN_SSH_HOST" ]]; then
  echo "ERROR: VEN_SSH_HOST must be set for vEN mode" >&2
  exit 2
fi

if [[ -z "$VEN_SSH_KEY" ]]; then
  echo "ERROR: VEN_SSH_KEY must be set to an SSH private key path for vEN mode" >&2
  exit 2
fi

if [[ ! -f "$VEN_SSH_KEY" ]]; then
  echo "ERROR: VEN_SSH_KEY file not found: $VEN_SSH_KEY" >&2
  exit 2
fi

echo "Validating SSH connectivity to vEN: ${VEN_SSH_USER}@${VEN_SSH_HOST}:${VEN_SSH_PORT}" >&2
ssh \
  -i "$VEN_SSH_KEY" \
  -p "$VEN_SSH_PORT" \
  -o StrictHostKeyChecking=no \
  -o UserKnownHostsFile=/dev/null \
  -o ConnectTimeout=10 \
  "${VEN_SSH_USER}@${VEN_SSH_HOST}" \
  -- sh -lc 'echo "vEN SSH OK"'

cat > .ven.env <<EOF
# Generated by scripts/ven/bootstrap.sh
export NODEGUID="${NODEGUID}"
export VEN_SSH_HOST="${VEN_SSH_HOST}"
export VEN_SSH_USER="${VEN_SSH_USER}"
export VEN_SSH_PORT="${VEN_SSH_PORT}"
export VEN_SSH_KEY="${VEN_SSH_KEY}"
EOF

chmod 0600 .ven.env
echo "Wrote $(pwd)/.ven.env" >&2
